### ISSUE TITLE
Can't start this

### ISSUE THREAD

**Issue by tomsoderlund** [afzydev/nodejs-express-socket.io-boilerplate#1]
Hi! This looks interesting!

I tried starting it with `node nodeServer.js` but got this error:

	TypeError: Cannot read property 'prototype' of undefined
		at Object.<anonymous> (/MYPROJECT/node_modules/socket.io/lib/store.js:35:41)
		at Module._compile (module.js:569:30)
		at Object.Module._extensions..js (module.js:580:10)
		at Module.load (module.js:503:32)
		at tryModuleLoad (module.js:466:12)
		at Function.Module._load (module.js:458:3)
		at Module.require (module.js:513:17)
		at require (internal/module.js:11:18)
		at Object.<anonymous> (/MYPROJECT/node_modules/socket.io/lib/manager.js:16:13)
		at Module._compile (module.js:569:30)

PS: no need to commit `node_modules` to the repository as long as `package.json` is up to date.

**Comment by afzydev** [comment]
Hi @tomsoderlund 
Can you please tell me the node version your using ?

**Comment by afzydev** [comment]
Hi @tomsoderlund 
1.First take a pull of master
2.npm install 
3.node nodeServer.js

Thanks for information, i have removed the **node_modules** folder :)
